####################################################################################################
# WatsonX configuration parameters
####################################################################################################
# provider: "watsonx"
# model: "ibm/granite-13b-chat-v2"
# project_id="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
# api_url: "https://eu-de.ml.cloud.ibm.com"
# parameters:
#   decoding_method: sample
#   min_new_tokens: 1
#   max_new_tokens: 500

####################################################################################################
# LLama.cpp configuration parameters
####################################################################################################
# provider: "llamacpp"
# model: "llama-2-7b-chat-gguf"
# transformers_path: "~/.cache/huggingface/transformers"
# model_path: "llama-2-7b-chat-gguf/llama-2-7b-chat.Q2_K.gguf"
# chat_format: "llama-2"

####################################################################################################
# Ollama configuration parameters
####################################################################################################
provider: "ollama"
model: "llama3"

####################################################################################################
# OpenAI configuration parameters
####################################################################################################
# provider: "openai"
# You can use:
# - "gpt-3.5-turbo" for ChatGPT 3.5
# - "gpt-4" for ChatGPT 4
# model: "llama-2-7b-chat"
# You can use:
# - https://api.openai.com/v1 for ChatGPT
# base_url: "http://localhost:8000/v1"
