####################################################################################################
# WatsonX configuration parameters
####################################################################################################
# provider: "watsonx"
# model: "ibm/granite-13b-chat-v2"
# project_id: "330903cb-a235-45c5-acbd-b15fb40858e7"
# api_url: "https://eu-de.ml.cloud.ibm.com"
# parameters:
#   decoding_method: greedy
#   min_new_tokens: 1
#   max_new_tokens: 500

####################################################################################################
# LLama.cpp configuration parameters
####################################################################################################
# provider: "llamacpp"
# model: "llama-2-7b-chat-gguf"
# transformers_path: "~/.cache/huggingface/transformers"
# model_path: "llama-2-7b-chat-gguf/llama-2-7b-chat.Q2_K.gguf"
# chat_format: "llama-2"

####################################################################################################
# Ollama configuration parameters
####################################################################################################
provider: "ollama"
model: "llama3"

####################################################################################################
# OpenAI configuration parameters
####################################################################################################
# provider: "openai"
# You can use:
# - "gpt-3.5-turbo" for ChatGPT 3.5
# - "gpt-4" for ChatGPT 4
# - "instructlab/merlinite-7b-lab" for InstructLab and Merlinite model
# model: "llama-2-7b-chat"
# You can use:
# - https://api.openai.com/v1 for ChatGPT
# base_url: "http://localhost:8000/v1"

####################################################################################################
# System Message Prompt
####################################################################################################
system_message: |
  You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe.
  Please ensure that your responses are socially unbiased and positive in nature.
  If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct.
  If you don't know the answer to a question, please don't share false information.