####################################################################################################
# HuggingFaces configuration parameters
####################################################################################################
provider: "huggingfaces"
model: "distilgpt2"