####################################################################################################
# Ollama configuration parameters
####################################################################################################
provider: "ollama"
model: "llama3"
