####################################################################################################
# OpenAI configuration parameters
####################################################################################################
provider: "openai"
model: "gpt-3.5-turbo"
# You can use GPT 4.0 too
# model: "gpt-4"
temperature: 0
