####################################################################################################
# WatsonX configuration parameters
####################################################################################################
provider: "watsonx"
model: "ibm/granite-13b-chat-v2"
project_id: "c189bcc3-b228-4a3d-b6f9-2817c587b178"
api_url: "https://us-south.ml.cloud.ibm.com"
parameters:
  decoding_method: greedy
  min_new_tokens: 1
  max_new_tokens: 100